GET http://127.0.0.1:3000/api/users HTTP/1.1

###

POST http://127.0.0.1:3000/api/users HTTP/1.1
content-type: application/json

{
    "firstname": "Jeremy",
    "lastname": "Doe",
    "email": "test111@email.com"
}

###
DELETE http://127.0.0.1:3000/api/users HTTP/1.1
content-type: application/json

{
    "email": "test111@email.com"
}

###
PATCH  http://127.0.0.1:3000/api/users HTTP/1.1
content-type: application/json

{
    "email": "test111@email.com",
    "firstname": "Jerimiah",
    "lastname": "From Amongus"
}